spring.application.name=quizmaster-backend

# CORS Configuration
security.cors.allowed-origins=http://localhost:5173

# JWT Configuration
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=86400s
security.jwt.cookie-name=access_token
security.jwt.cookie-secure=false
security.jwt.cookie-same-site=Lax